//
//  Notifications.h
//  DSMenu
//
//  Created by Jonas Schnelli on 02.07.14.
//  Copyright (c) 2014 include7. All rights reserved.
//

/**
 * \ingroup core
 */

#ifndef DSMenu_Notifications_h
#define DSMenu_Notifications_h

#define kMD_NOTIFICATION_HOST_DID_CHANGE @"MDNotificationHostDidChange"
#define kMD_NOTIFICATION_APPTOKEN_DID_CHANGE @"MDNotificationAppTokenDidChange"

#define kDS_CONSUMPTION_DID_CHANGE @"CONSUMPTION_DID_CHANGE"
#define kDS_STRUCTURE_DID_CHANGE @"STRUCTURE_DID_CHANGE"
#define kDS_START_LOADING_STRUCTURE @"START_LOADING_STRUCTURE"

#define kDS_DSS_AUTH_ERROR @"DS_DSS_AUTH_ERROR"

#define kDS_SHOULD_TRY_TO_RELOAD_STRUCTURE @"SHOULD_TRY_TO_RELOAD_STRUCTURE"

#define kDS_SHOULD_START_POLLING_CONSUMPTION_DATA @"SHOULD_START_POLLING_CONSUMPTION_DATA"
#define kDS_SHOULD_STOP_POLLING_CONSUMPTION_DATA @"SHOULD_STOP_POLLING_CONSUMPTION_DATA"

#endif
